import React from "react";

export const metadata = {
  title: "Sản phẩm ?",
  description: "Generated by create next app",
};
export default function layout({ children }) {
  return <>{children}</>;
}
