// import Image from "next/image";
import ListItem from "./components/ListItem/page"; // Đường dẫn tương đối đến file page.js
export const metadata = {
  title: "Newseven",
  description: "Generated by create next app",
};
export default function Home() {
  const products = [
    {
      id: 1,
      name: "product 1",
      des: "packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like",
      price: "100",
    },
    {
      id: 2,
      name: "product 2",
      des: "packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like",
      price: "100",
    },
    {
      id: 3,
      name: "product 3",
      des: "packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like",
      price: "100",
    },
    {
      id: 4,
      name: "product 4",
      des: "packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like",
      price: "100",
    },
  ];
  return (
    <div className="p-[3rem] flex gap-4 w-full justify-center">
      {products.map((item) => (
        <ListItem key={item.id} {...item}></ListItem>
      ))}
    </div>
  );
}
