import Products from "./(components)/Products/page";

export const metadata = {
  title: "Newseven",
  description: "Generated by create next app",
};

export default function Home() {
  return <Products />;
}
